import type { Metadata } from "next";
import { Poppins,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";
import Footer from "@/components/Footer";
import {Toaster} from "sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "WareSpace",
  description: "Generated by create next app",
  icons:["/logo.svg"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${poppins.variable} ${roboto.variable} antialiased`}
    >
    <Toaster position="top-right"/>
    <div id="loading-root"/>
    <Navbar/>
    <main className="min-h-screen">
        {children}
    </main>
    <Footer/>
    </body>
    </html>
  );
}
